export { HomePage } from './homepage/HomePage'
export { NewsPage } from './newspage/NewsPage'
export { News } from './newspage/newsComponent'
export { UsefulPage } from './usefulpage/UsefulPage'

export { AboutUsPage } from './aboutblock/aboutuspage/AboutUsPage'
export { AssetPage } from './aboutblock/assetpage/AssetPage'
export { ContactsPage } from './aboutblock/contactspage/ContactsPage'

export { AiremissionsPage } from './projectsblock/airemissionspage/AiremissionsPage'
export { EcopoliticPage } from './projectsblock/ecopoliticpage/EcopoliticPage'
export { InitiativesPage } from './projectsblock/initiativespage/InitiativesPage'
export { EcomanagePage } from './projectsblock/ecomanagepage/EcomanagePage'
export { OuractivitiesPage } from './projectsblock/ouractivitiespage/OuractivitiesPage'
export { EventsPage } from './projectsblock/eventspage/EventsPage'
